"""
gis_tab.py
----------
Streamlit tab for interactive Folium maps and GIS field zoning.
"""

from __future__ import annotations

import streamlit as st

def render():
    st.header("Field Zoning & GIS Maps")
    
    if "multispectral_stack" not in st.session_state:
        st.warning("Please upload imagery in the Upload tab first.")
        return
        
    st.markdown("Interactive management zones based on NDVI and stress thresholds.")
    
    st.info("Folium map placeholder. This would display the folium map generated by `src.gis.folium_maps.zone_choropleth`.")
    st.image(st.session_state.rgb_image, caption="Zone Map (Mock)", use_column_width=True)
